### ISSUE TITLE
@sanity/vision/lib/index.esm.js not found

### ISSUE THREAD

**Issue by shaunchander** [sanity-io/sanity-plugin-asset-source-unsplash#66]
Using `sanity-plugin-asset-source-unsplash` with `sanity@dev-preview` and `@sanity/vision@^3.0.0-rc.2` results in the following issue:

```
Error: ENOENT: no such file or directory, open '/Users/shaun/Desktop/work/bitfo/node_modules/@sanity/vision/lib/index.esm.js'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at extractExportsData (file:///Users/shaun/Desktop/work/bitfo/node_modules/vite/dist/node/chunks/dep-c842e491.js:42970:31)
    at async runOptimizeDeps (file:///Users/shaun/Desktop/work/bitfo/node_modules/vite/dist/node/chunks/dep-c842e491.js:42647:29)
    at async optimizeNewDeps (file:///Users/shaun/Desktop/work/bitfo/node_modules/vite/dist/node/chunks/dep-c842e491.js:42050:16)
    at async runOptimizer (file:///Users/shaun/Desktop/work/bitfo/node_modules/vite/dist/node/chunks/dep-c842e491.js:42079:55)
```

It looks like a depedency within the plugin is expecting `@sanity/vision` to export from a `index.esm.js` file but inspecting the package, it only exports from an `index.cjs` file.

I'm on a Mac M1 // OSX Ventura if that's relevant to the issue.

**Comment by stipsan** [comment]
Running `npm i sanity@latest @sanity/vision@latest sanity-plugin-asset-source-unsplash@latest` should resolve this issue 🙂
